### ISSUE TITLE
Ruins Invalid Data Report - GR3 - D07

### ISSUE THREAD

**Issue by AJRGale** [canonn-science/GR-RuinsComboMap#124]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name: 
CMDR Peter Cornell

## Which Ruins Site? 
GR3

## Which Obelisk ID? 
D07

## What data did you get? 
Culture 5

## What combo did you use? 
Orb + Tablet

## Other Questions/Comments/Concerns

**Comment by roivanov** [comment]
Actually, both D07 and D12 needs Orb + Tablet.
But decoding has failed for me, tried both OrTa and ToTa
