### ISSUE TITLE
Ruins Invalid Data Report - GR11 - D07

### ISSUE THREAD

**Issue by Tromador** [canonn-science/GR-RuinsComboMap#141]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
CMDR Tromador

## Which Ruins Site?
GR11

## Which Obelisk ID?
D07

## What data did you get?
Nothing

## What combo did you use?
Orb & Tablet

## Other Questions/Comments/Concerns
Clearly I'm using the correct combination of items, but get nothing.
See screenshot.

![07-11-2018 01-35-58 synuefe tp-f b44-0-synuefe tp-f b44-0 cd 1](https://user-images.githubusercontent.com/38956076/42546037-3c48ce58-84b3-11e8-8f94-34c6771d51a6.png)

**Comment by Tromador** [comment]
UPDATE: The Obelisk does give C5 if scanned with ToTa, despite the obvious inconsistency in the inconography of the obelisk.

**Comment by derrickmehaffy** [comment]
@Tromador for Alpha - D7 (GR11) we do have Culture 5 marked with Totem & tablet in our API. This is likely a bug with the game itself. I have spoken with FDev and the short answer is "Won't fix".

For Beta I7 we have it listed as History 9 with Casket/Casket.

That being said you are also welcome to open bug reports on the FDev forum for these cases too.

**Comment by Tromador** [comment]
Well, I have done so @ 
https://forums.frontier.co.uk/showthread.php/438581-Incorrect-Iconography-on-Guardian-Obelisk-for-Ram-Tah-Mission-quot-Decoding-the-Ancient-Ruins-quot

Be interesting to see the response (if any).

**Comment by Tromador** [comment]
QA-Jack 
Frontier QA Team 
Frontier Employee
Hey Tromador,

Thanks for your report - This is something we are aware of and currently looking into. I have added your info and bumped the issue internally.

Stay safe out there o7
