### ISSUE TITLE
Ruins Invalid Data Report - GS1 - D06

### ISSUE THREAD

**Issue by CMDRNigelHans** [canonn-science/GR-RuinsComboMap#68]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
Example: CMDR Nigel Hans

## Which Ruins Site?
 GS01

## Which Obelisk ID?
 D06

## What data did you get?
 none

## What combo did you use?
 all of them

## Other Questions/Comments/Concerns
the map says its verified for CaCa but i tried and it doesnt work, indicated its for History 9, but History 9 is A08 which I can verify is teh case, maybe it was changed in 2.4 but I cant figure out what its supposed to be

Regards
 -CMDR Nigel Hans

**Comment by Supafuzz916** [comment]
Are you saying you had already scanned A08 and gotten History 9 because if you had already scanned a History 9 then you will get no response if you try to scan another Histiory 9 obelisk.

**Comment by derrickmehaffy** [comment]
Resolving due to user not responding.
