### ISSUE TITLE
Ruins Invalid Data Report - GR11 - C01

### ISSUE THREAD

**Issue by PLasturo** [canonn-science/GR-RuinsComboMap#70]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
Plasturo

## Which Ruins Site?
GS11

## Which Obelisk ID?
C01

## What data did you get?
Bio 4

## What combo did you use?
Totem + Urn

**Comment by Supafuzz916** [comment]
C01 still gives Cul 04 With totem + urn

![synuefe tp-f b44-0 11-13-2017 7-43-25 pm](https://user-images.githubusercontent.com/29947048/32745651-50ae139c-c881-11e7-8a1f-ce4d6e86a155.jpg)
