### ISSUE TITLE
Ruins Invalid Data Report - GR35 - M01

### ISSUE THREAD

**Issue by Andy-Gill** [canonn-science/GR-RuinsComboMap#72]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
Example: CMDR Saool

## Which Ruins Site?
Example: GS35

## Which Obelisk ID?
Example: M01

## What data did you get?
Example: Unable to activate

## What combo did you use?
Example: Tablet

## Other Questions/Comments/Concerns
Assuming it was not bugged that this Monolith is not activated by a single tablet, or does not give Language 1. I do not have Language 1 but keep getting told I have the date from this node.

**Comment by Supafuzz916** [comment]
M01 still gives Lang 1 with tab only

![col 173 sector ly-q d5-59 11-13-2017 7-18-40 pm](https://user-images.githubusercontent.com/29947048/32744531-c9f19228-c87d-11e7-94ad-c1a31541dd57.jpg)
