### ISSUE TITLE
Ruins Invalid Data Report - GR215 - I14

### ISSUE THREAD

**Issue by Cholerix** [canonn-science/GR-RuinsComboMap#73]
## Your CMDR Name:
CMDR Cholerix

## Which Ruins Site?
GS215

## Which Obelisk ID?
I14

The ruin map says Urn+Orb should give me Biology 5. I believe I recieved pattern data but I didn't get Biology 5. Afterwards I went to GS208 where the same combination on Obelisk F19 gave me Biology 5 so I did infact not recieve it before.

I don't know if you maintain the route planner at edshipyard. On that list the obelisk GS215-I14 is marked with a questionmark.

**Comment by Supafuzz916** [comment]
I identified the wrong active obelisk. I10 was misidentified as I14. Spreadsheet and the API have been corrected . The route planner should update itself with the correct information.
