### ISSUE TITLE
Ruins Invalid Data Report - GR47 - O16

### ISSUE THREAD

**Issue by DeadManBrooding** [canonn-science/GR-RuinsComboMap#74]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
CMDR Heermeyster

## Which Ruins Site?
GR47

## Which Obelisk ID?
O16

## What data did you get?
Technology 9

## What combo did you use?
Orb + Casket

## Other Questions/Comments/Concerns
Been to site GR4 before, scanned B04 with same item combo, got Tech 9, as noted on respective map. Got no info from GR47/O16, hence it's probably the same, as I have no other Tech data. Can confirm correctness of everything else regarding sites GR47 and GR4, though.

**Comment by DeadManBrooding** [comment]
Revisited site on return flight. Got Tech 3 now after rechecking O16, for some reason. Anyway, I guess this can be closed, then.

**Comment by derrickmehaffy** [comment]
User issue resolved itself.
